// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ParcialWebContext))]
    [Migration("20211026130352_InitialCreate5")]
    partial class InitialCreate5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidad.Infraccion", b =>
                {
                    b.Property<int>("IdInfraccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoInf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionInf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInfraccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaIdentificacion")
                        .HasColumnType("int");

                    b.Property<int>("ValorInf")
                        .HasColumnType("int");

                    b.HasKey("IdInfraccion");

                    b.HasIndex("PersonaIdentificacion");

                    b.ToTable("Infracciones");
                });

            modelBuilder.Entity("Entidad.Persona", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entidad.Infraccion", b =>
                {
                    b.HasOne("Entidad.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaIdentificacion");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
